#!/bin/sh

# set -x
set -e

MOD_FILES=$(git diff --diff-filter=d --cached --name-only)
DATE=$(date +%d\\/%m\\/%Y)
while IFS= read -r FILE_NAME; do
	if [[ "${FILE_NAME}" =~ \.md ]] && [[ ! "${FILE_NAME}" = "README.md" ]] && [[ "${FILE_NAME}" == spark-sessions* ]] && [[ "$(basename "${FILE_NAME}")" == SparkSession* ]]; then
		if [[ "$OSTYPE" == "linux-gnu"* ]]; then
			sed -i "2s/.*/\*updated\: $DATE\*/" "$FILE_NAME"
		else
			sed -i '' "2s/.*/\*updated\: $DATE\*/" "$FILE_NAME"
		fi
		echo "Updated date to: ${DATE}"
		git add "$FILE_NAME"
		if [ ! -f "markdown-to-pdf/build/app.js" ]; then
			CURRENT_PWD=$(pwd)
			cd markdown-to-pdf/
			npm install
			npm run build
			cd "$CURRENT_PWD"
		fi
		FILE=$(basename "$FILE_NAME")
		NAME="${FILE%.*}.pdf"
		node markdown-to-pdf/build/app.js "$FILE_NAME" "pdfs/$NAME"
		git add "pdfs/$NAME"
		echo
	fi
done <<< "$MOD_FILES"

exit 0
